# Generated by Django 4.1.2 on 2022-11-13 14:04

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', users.managers.AppUserManager()),
            ],
        ),
    ]
