# Generated by Django 4.1.2 on 2022-11-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
