# Generated by Django 4.1.2 on 2022-12-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('gaming', 'gaming'), ('toys', 'toys'), ('books', 'books'), ('music', 'music'), ('clothes', 'clothes'), ('pc_laptops', 'pc_laptops'), ('phones', 'phones'), ('tv_monitors', 'tv_monitors')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
