# Generated by Django 4.1.2 on 2022-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_products_img_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('gaming', 'gaming'), ('toys', 'toys'), ('books', 'books'), ('music', 'music'), ('clothes', 'clothes'), ('pc_laptops', 'pc_laptops'), ('phones', 'phones'), ('tv_monitors', 'tv_monitors')], max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='products'),
        ),
    ]
