# Generated by Django 4.1.2 on 2022-12-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
