# Generated by Django 4.1.2 on 2022-12-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_img1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_img2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_img3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_img4',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_img5',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
