# Generated by Django 4.0 on 2022-12-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_sub_img1_products_sub_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidingAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
