# Generated by Django 4.1.2 on 2022-12-13 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_slidingads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidingAdds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.DeleteModel(
            name='SlidingAds',
        ),
    ]
