# Generated by Django 4.1.2 on 2022-12-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_slidingadds_delete_slidingads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
