# Generated by Django 4.0 on 2022-12-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_smallads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallAds',
        ),
    ]
