# Generated by Django 4.0 on 2022-12-16 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_smallads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallAds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filter_word', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='products')),
            ],
        ),
    ]
